apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auditoria-nfs-pvc
  namespace: tipsbank-auditoria
  labels:
    app: auditoria
    {{- include "tipsbank.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.auditoria.storage.accessModes | nindent 4 }}
  {{- if .Values.auditoria.storage.storageClassName }}
  storageClassName: {{ .Values.auditoria.storage.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.auditoria.storage.size }}
