apiVersion: v1
kind: Secret
metadata:
  name: contas-db-secret
  namespace: tipsbank-contas
  labels:
    app: postgres
    {{- include "tipsbank.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.contas.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.contas.postgres.password | quote }}
  POSTGRES_DB: {{ .Values.contas.postgres.db | quote }}
  DB_URL: {{ include "tipsbank.contas.dburl" . | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-secret
  namespace: tipsbank-contas
  labels:
    {{- include "tipsbank.labels" . | nindent 4 }}
type: Opaque
data:
  auth: {{ .Values.contas.basicAuth.auth }}
