# kubectl apply -f pod.yaml
# kubectl delete -f pod.yaml
apiVersion: v1 
kind: Pod 
metadata: 
  labels:
    run: desafio
  name: desafio
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts:
    - mountPath: /desafio
      name: volume-empty-desafio
    resources:
      limits:
        cpu: "0.7"
        memory: "246Mi"
      requests:
        cpu: "0.4"
        memory: "128Mi"
  - image: busybox
    name: busybox
    args: 
      - sleep 
      - "600"
    resources:
      limits:
        cpu: "0.4"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"

  dnsPolicy: ClusterFirst 
  restartPolicy: Always
  volumes:
  - name: volume-empty-desafio
    emptyDir: 
      sizeLimit: "64Mi"