apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-db
spec:
  selector:
    matchLabels:
      app: database
  serviceName: "db-service"
  replicas: 3
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_PASSWORD
          value: "senhaforte"
  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: aws-sc-fast
      resources:
        requests:
          storage: 1Gi
