apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-clone-qa
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: aws-sc-fast
  dataSource:
    kind: PersistentVolumeClaim
    name: web-pvc

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-storage-pod-clone-qa
  labels:
    app.kubernetes.io/name: nginx-storage-pod-clone-qa
spec:
  containers:
  - name: nginx-storage-pod-clone-qa
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    ports:
      - containerPort: 80
    volumeMounts:
      - name: web-pvc
        mountPath: /usr/share/nginx/html
  volumes:
    - name: web-pvc
      persistentVolumeClaim:
        claimName: pvc-clone-qa