apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gpu-affinity-prefered
spec:
  selector:
    matchLabels:
      app: nginx-gpu-affinity-prefered
  template:
    metadata:
      labels:
        app: nginx-gpu-affinity-prefered
    spec:
      containers:
      - name: nginx-gpu-affinity-prefered
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nginx-gpu-affinity-prefered
            topologyKey: "kubernetes.io/hostname"
