apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nfs
spec:
  selector:
    matchLabels:
      app: nginx-nfs
  template:
    metadata:
      labels:
        app: nginx-nfs
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: licaodecasa-pvc
          mountPath: /usr/share/nginx/html
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "300m"
      volumes:
      - name: licaodecasa-pvc
        persistentVolumeClaim:
          claimName: licaodecasa-pvc

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: licaodecasa
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: licaodecasa-pv
  labels:
    storage: nfs
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: licaodecasa
  nfs:
    path: /mnt/nfs/nginx
    server: 172.30.189.122

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: licaodecasa-pvc
spec:
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: licaodecasa
  selector:
    matchLabels:
      storage: nfs



