apiVersion: v1
kind: Secret
metadata:
  name: transacoes-db-secret
  namespace: tipsbank-transacoes
  labels:
    {{- include "tipsbank.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_URL: {{ include "tipsbank.transacoes.dburl" . | quote }}
