---
apiVersion: v1
kind: Service
metadata:
  name: postgres-replica
  namespace: tipsbank-contas
  labels:
    app: postgres
    role: replica
spec:
  clusterIP: None
  selector:
    app: postgres
    role: replica
  ports:
    - port: 5432
      name: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-replica
  namespace: tipsbank-contas
spec:
  serviceName: postgres-replica
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      role: replica
  template:
    metadata:
      labels:
        app: postgres
        role: replica
    spec:
      tolerations:
        - key: "compliance"
          operator: "Equal"
          value: "strict"
          effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: postgres
              topologyKey: kubernetes.io/hostname
      initContainers:
        - name: wait-primary
          image: busybox:1.36
          command:
            - sh
            - -c
            - "until nc -zw3 postgres.tipsbank-contas.svc.cluster.local 5432; do echo 'aguardando primary...'; sleep 3; done"
      containers:
        - name: postgres-replica
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: tipsbank
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: contas-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: contas-db-secret
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          startupProbe:
            exec:
              command: ["pg_isready", "-U", "tipsbank", "-d", "tipsbank"]
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "tipsbank", "-d", "tipsbank"]
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "tipsbank", "-d", "tipsbank"]
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 6
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: init-sql
          configMap:
            name: postgres-init-sql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi