---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-contas
  namespace: tipsbank-contas
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: api-contas
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-transacoes
  namespace: tipsbank-transacoes
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: api-transacoes
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auditoria
  namespace: tipsbank-auditoria
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: auditoria
  endpoints:
    - port: http
      path: /metrics
      interval: 15s